# Site settings
title: "Felipe Skroski - Web design, mobile UX and UI"
email: felipeskroski@gmail.com
description: "I'm Felipe Skroski a designer & developer based in Wellington, New Zealand. I create products for web and mobile. Working for over 12 years with organisations ranging from dynamic startups to large corporations located around the globe."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://felipeskroski.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
